mipi_display: fix undeclared CONFIG_MIPI_DISPLAY_PIN_BL_ACTIVE
m5stack-core2.defaults currently fails to build:

 mipi_display.c: In function 'mipi_display_init':
 mipi_display.c:253:52: error: 'CONFIG_MIPI_DISPLAY_PIN_BL_ACTIVE' undeclared (first use in this function); did you mean 'CONFIG_MIPI_DISPLAY_PIN_BL'?
         gpio_set_level(CONFIG_MIPI_DISPLAY_PIN_BL, CONFIG_MIPI_DISPLAY_PIN_BL_ACTIVE);
                                                    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

So lets fix it, by making CONFIG_MIPI_DISPLAY_PIN_BL build time config
option, since it doesn't make sense to make it runtime config option
anyway and this was probably initially intended.

Do the same with CONFIG_MIPI_DISPLAY_PWM_BL as well.

Signed-off-by: Petr Štetiar <ynezz@true.cz>