mipi_display: fix missing esp_rom_gpio_pad_select_gpio header
Currently the project doesn't build with IDF versions v4.4 and v5.0:

 mipi_display.c: In function 'mipi_display_init':
 mipi_display.c:204:9: error: implicit declaration of function 'esp_rom_gpio_pad_select_gpio'; did you mean 'gpio_pad_select_gpio'? [-Werror=implicit-function-declaration]
         esp_rom_gpio_pad_select_gpio(CONFIG_MIPI_DISPLAY_PIN_CS);
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
         gpio_pad_select_gpio

So lets fix it by adding a missing `esp_rom_gpio.h` header.

Signed-off-by: Petr Štetiar <ynezz@true.cz>